/****** Script for SelectTopNRows command from SSMS  ******/
INSERT INTO [pplanner].[dbo].[Resources]
VALUES ('Projects','BreadCrumbCreateProjectSecond',N'Създаване на нов проект'),
('Projects','BreadCrumbDeleteProjectSecond',N'Изтриване на проект'),
('Projects','BreadCrumbEditProjectSecond',N'Редакция на проект'),
('Projects','BreadCrumbProjectDetailsSecond',N'Преглед'),
('Projects','BreadCrumbProjectListFirst',N'Списък с проекти'),
('Projects','EditProjectHeaderTxt',N'Редакция на проект: '),
('Projects','EditProjectTitle',N'Редакция на проект'),
('Projects','ProjectBurnDownChart',N'BurnDown графика'),
('Projects','ProjectCreateHeading',N'Въведете основни данни за проекта '),
('Projects','ProjectCreateHeadingTxt',N'Създаване на проект'),
('Projects','ProjectCreateTitle',N'Създаване на нов проект'),
('Projects','ProjectCurrentSprint',N'Текущ спринт'),
('Projects','ProjectDateValidationMessage',N'(Дата неможе да е преди днес)'),
('Projects','ProjectDaysValidationMessage',N'(От 2 до 60 дни)'),
('Projects','ProjectDeleteHeading',N'Изтриване на проект '),
('Projects','ProjectDeleteHeadingTxt',N'Проект: '),
('Projects','ProjectDeleteTitle',N'Изтриване на проект'),
('Projects','ProjectDetailsHeaderTxt',N'Проект: '),
('Projects','ProjectDetailsTitle',N'Детайли за проект'),
('Projects','ProjectEndDate',N'Крайна дата'),
('Projects','ProjectIterationDays',N'Дни за итерация'),
('Projects','ProjectLeftDays',N'Оставащи дни'),
('Projects','ProjectList',N'Списък с текущи проектии'),
('Projects','ProjectName',N'Име на проект'),
('Projects','ProjectOnlyWorkingDaysMessage',N'Само работни дни'),
('Projects','ProjectPeriod',N'Период на проекта'),
('Projects','ProjectScrumMaster',N'Scrum master'),
('Projects','ProjectStartDate',N'Начална дата'),
('Projects','ProjectTotalDays',N'от общо'),
('Buttons','BackButton',N'Назад'),
('Buttons','BacklogButton',N'Backlog'),
('Buttons','CreateProjectButton',N'Нов проект'),
('Buttons','DeleteButton',N'Изтрий'),
('Buttons','EditButton',N'Редакция'),
('Buttons','NoData',N'Няма данни'),
('Buttons','PleaseWait',N'Моля изберете...'),
('Buttons','SaveButton',N'Запиши'),
('Buttons','ScrumboardButton',N'Scrumboard'),
('Buttons','TasksButton',N'Задачи'),
('Buttons','ChangeAvatar',N'Промяна на снимка'),
('Account','AgainPassword',N'Повтори парола'),
('Account','BreadCrumbChangePasswordSecond',N'Смяна на парола'),
('Account','BreadCrumbEditUserSecond',N'Редакция на профил'),
('Account','BreadCrumbUserDetailsSecond',N'Преглед на профил'),
('Account','BreadCrumbUserManageFirst',N'Потребители'),
('Account','BreadCrumbUserManageSecond',N'Списък с потребители'),
('Account','BreadCrumbUserRolesSecond',N'Списък с роли'),
('Account','ChangePassword',N'Смяна на парола'),
('Account','EditTitle',N'Редакция на профил'),
('Account','Email',N'Електронна поща'),
('Account','Login',N'Вход'),
('Account','LoginHeaderTxt',N'Вход в системата'),
('Account','LoginTitle',N'Вход в системата'),
('Account','Logout',N'Изход'),
('Account','Password',N'Парола'),
('Account','Position',N'Длъжност'),
('Account','Profile',N'Личен профил'),
('Account','Register',N'Регистрация'),
('Account','RegisterHeaderTxt',N'Регистране на профил'),
('Account','RegisterTitle',N'Регистрация'),
('Account','RememberMe',N'Запомни ме'),
('Account','Role',N'Роля'),
('Account','Settings',N'Настройки'),
('Account','Status',N'Статус'),
('Account','TasksList',N'Списък със задачи'),
('Account','UserDetailsHeaderTxt',N'Детайли за потребител'),
('Account','UserDetailsTitle',N'Профил на'),
('Account','UserFirstName',N'Име'),
('Account','UserFullName',N'Име на потребителя'),
('Account','UserLastName',N'Фамилия'),
('Account','UserManage',N'Управление на потребители'),
('Account','UserManageHeader',N'Управление на потребителски профили'),
('Account','UserManageTitle',N'Управление на потребители'),
('Account','UserName',N'Потребителско име'),
('Account','UserNewPassword',N'Нова парола'),
('Account','UserOldPassword',N'Стара парола'),
('Account','UserProfileTitle',N'Смяна на парола за потребителски профил: '),
('Account','UserRoles',N'Потребителски роли'),
('Account','UserRolesTitle',N'Потребителски роли'),
('Sprint','SprintEndDate',N'Дата на приключване'),
('Sprint','SprintName',N'Име на спринт'),
('Sprint','SprintStartDate',N'Дата на стартиране'),
('Sprint','SprintStatus',N'Статус'),
('Sprint','SprintStatusCompleted',N'Завършена'),
('Sprint','SprintStatusUndone',N'Незавършена'),
('Sprint','SprintStatusWorking',N'Текуща'),
('Task','TaskDate',N'Дата на завършване'),
('Task','TaskEffort',N'Усилие'),
('Task','TaskName',N'Име'),
('Task','TaskPriority',N'Приоритет'),
('Task','TaskProject',N'Проект'),
('Task','TaskSprint',N'Спринт'),
('Buttons','CreateButton',N'Нов'),
('Resource','ResourcesIndexHeadingTxt',N'Списък с ресурси в системата'),
('Resource','BreadCrumbResourcesFirst',N'Ресурси'),
('Resource','BreadCrumbResourcesSecond',N'Списък'),
('Resource','ResourceIndexTitle',N'Списък с ресурси'),
('Resource','ResourceIndexId',N'ID'),
('Resource','ResourceIndexGroup',N'Група'),
('Resource','ResourceIndexName',N'Име на ресурса'),
('Resource','ResourceIndexValue',N'Стойност на ресурса'),
('Resource','ResourceGroup',N'Група'),
('Resource','ResourceCreateHeadingTxt',N'Създаване на нов ресурс'),
('Resource','ResourceCreateGroup',N'Група'),
('Resource','ResourceCreateName',N'Име на ресурс'),
('Resource','ResourceCreateValue',N'Стойност на ресурс'),
('Buttons','PleaseEnterText',N'Моля въведете текст ...'),
('Resource','BreadCrumbResourcesCreateSecond',N'Създаване на нов ресурс'),
('Resource','ResourceCreateTitle',N'Създаване на ресурс'),
('Resource','BreadCrumbResourcesEditSecond',N'Редакция на ресурс'),
('Resource','ResourceEditTitle',N'Редакция на ресурс'),
('Resource','ResourceEditHeadingTxt',N'Редакция на ресурс'),
('Buttons','ResourcesButton',N'Управление на ресурси'),
('Buttons','EffortPlaceholder',N'Усилие между 1 и 10'),
('Buttons','test123',N'hahahaha'),
('Buttons','UpdateFromCSVFile',N'Актуализирай от CSV'),
('Buttons','UndoneTasksInProject',N'Неизпълнени задачи'),
('Buttons','DownloadAllInCSVFile',N'Изтегли темплейт'),
('Account','AccountManageTitle',N'Профил на '),
('Account','BreadCrumbUserProfileFirst',N'Потребителски профил на '),
('Account','test',N'1234'),
('Buttons','PleaseEnterEmailText',N'Моля въведете електронен адрес ...'),
('Backlog','BackLogEditTitle',N'Редакция на задача'),
('Backlog','BreadCrumbBacklogEditSecond',N'Редакция на задача'),
('Backlog','BacklogEditHeadingTxt',N'Задача: '),
('Backlog','BacklogEditInProject',N'към проект: '),
('Task','BacklogEditUserName',N'Потребител'),
('Task','BacklogEditStatus',N'Статус'),
('Task','BacklogUserEditTaskEffortCorrection',N'Корекция на усилието'),
('Buttons','PleaseEnterNum',N'Моля въведете число ...'),
('Projects','ProjectEditSprintSettingsIteration',N'Настройка на итерацията'),
('Buttons','NewListButton',N'Нов списък'),
('Projects','BreadCrumbProjectEditSprintSecond',N'Настройка на итерация'),
('Projects','ProjectEditSprintsTitle',N'Редакция на итерация'),
('Sprint','SprintEditTitle',N'Редакция'),
('Sprint','BreadCrumbSprintEditSecond',N'Редакция на задачa'),
('Sprint','SprintEditInSprint',N'към спринт: '),
('Sprint','SprintEditTaskName',N'Име на задача'),
('Sprint','SprintEditEffort',N'Усилие'),
('Sprint','SprintEditUserInRole',N'Отговорен потребител'),
('Sprint','SprintEditStatus',N'Статус'),
('Account','AccountUploadImageTitle',N'Промяна на снимка'),
('Buttons','ChangeButton',N'Промени'),
('Account','AccountUploadImageHeadingTxt',N'Промяна на профилна снимка'),
('Account','AccountUploadImageInputTitle',N'Изображение'),
('Backlog','BacklogDeleteTitle',N'Изтриване на задача '),
('Backlog','BreadCrumbBacklogDeleteSecond',N'Изтриване на задача'),
('Backlog','BacklogDeleteHeaderTxt',N'Проект: '),
('Backlog','BacklogDeleteTaskName',N'Име на задачата'),
('Backlog','BacklogDeletePriority',N'Приоритет'),
('Backlog','BacklogDeleteEffort',N'Усилие'),
('Backlog','BacklogDeleteProjectName',N'Име на проект'),
('Backlog','BacklogDeleteTaskStatus',N'Статус на задачата'),
('Backlog','BacklogDeleteSprint',N'Спринт'),
('Backlog','BacklogDeleteInProject',N'към проект: '),
('Backlog','BacklogDetailsTitle',N'Детайли за '),
('Backlog','BreadCrumbBacklogDetailsSecond',N'Детайли за задача'),
('Buttons','CorrectionButton',N'Корекция'),
('Backlog','BacklogDetailsTaskName',N'Име на задача'),
('Backlog','BacklogDetailsPriority',N'Приоритет'),
('Backlog','BacklogDetailsEffort',N'Усилие'),
('Backlog','BacklogDetailsUsername',N'Потребител'),
('Backlog','BacklogDetailsProjectName',N'Име на проект'),
('Backlog','BacklogDetailsStatus',N'Статус'),
('Backlog','BacklogDetailsSprintName',N'Име на спринт'),
('Backlog','BacklogDetailsInProject',N'към проект:'),
('Backlog','BacklogIndexTitle',N'Backlog'),
('Backlog','BreadCrumbBacklogIndexSecond',N'Backlog'),
('Backlog','BacklogIndexHeaderTxt',N'Проект: '),
('Buttons','SettingsButton',N'Настройка'),
('Backlog','BacklogIndexHeader',N'Добавяне на нова задача'),
('Buttons','AddButton',N'Добави'),
('Backlog','BacklogIndexWriteTaskTitle',N'Въведете име за нова задача'),
('Backlog','BacklogIndexName',N'Име'),
('Backlog','BacklogIndexStatus',N'Статус'),
('Backlog','BacklogIndexPriority',N'Приоритет'),
('Backlog','BacklogIndexEffort',N'Усилие'),
('Backlog','BacklogIndexSprint',N'Итерация'),
('Backlog','BacklogIndexUsername',N'Потребител'),
('Buttons','NoResultsAddNewTasks',N'Няма намерени резултати. Добавете нови задачи от менюто по-горе.'),
('Sprint','IterationPartialSprintTableName',N'Име'),
('Sprint','IterationPartialSprintTableStartDate',N'Дата на стартиране'),
('Sprint','IterationPartialSprintTableEndDate',N'Дата на приключване'),
('Projects','ProjectIndexTitle',N'Списък с проекти'),
('Projects','ProjectTasksTitle',N'Персонални задачи'),
('Projects','BreadCrumbProjectTaskSecond',N'Списък със задачи'),
('Projects','ProjectTasksHeadingTxt',N'Задачи за деня'),
('Projects','ProjectUndoneTitle',N'Неизпълнени задачи'),
('Projects','ProjectUndoneHeadingTxt',N'Списък с неизпълнени задачи'),
('Projects','ProjectUndoneName',N'Име'),
('Projects','ProjectUndoneStatus',N'Статус'),
('Projects','ProjectUndoneEffort',N'Усилие'),
('Projects','ProjectUndoneIteration',N'Итерация'),
('Projects','ProjectUndoneUsername',N'Потребител'),
('Buttons','NoResultsFounded',N'Няма намерени резултати.'),
('Resource','ResourcesUpdateTitle',N'Актуализация на ресурси'),
('Resource','BreadCrumbResourcesUpdateSecond',N'Актуализация'),
('Resource','ResourceUpdateHeadingTxt',N'Актуализация на ресурсите в системата'),
('Resource','CreateNewResourceButton',N'Нов ресурс'),
('Resource','InitiateNewButton',N'Създай'),
('Resource','ResourceUpdateFileUpload',N'Прикачи файл'),
('Buttons','ToDo',N'За изпълнение'),
('Buttons','Done',N'Изпълнени'),
('Buttons','InProgress',N'В процес на разработка'),
('Resource','SprintboardTitle',N'Sprintboard'),
('Resource','BreadCrumbSprintboardFirst',N'Sprintboard'),
('Resource','BreadCrumbSprintboardSecond',N'Преглед'),
('Sprint','SprintSprintboardIndexHeadingTxt',N'Спринт: '),
('Buttons','CompleteButton',N'Завърши'),
('Projects','ProjectDetailsCurrentSprintCountTasks',N'Текущи задачи'),
('Projects','DevelopersList',N'Списък с потребители'),
('Projects','ProjectDetailsDeveloperList',N'Име на потребител (потребителско име)'),
('Projects','ProjectDetailsDeveloperAllTasks',N'Брой задачи'),
('Projects','ProjectDetailsDeveloperLastTasks',N'Неизпълнени задачи'),
('Projects','NoRightsToSeeThis',N'Нямате права за достъп до този проект. Моля обърнете се към системен администратор.'),
('Sprint','SprintIndexActiveUsersHeadingTxt',N'Активни потребители'),
('Sprint','SprintIndexEffort',N'Усилие'),
('Sprint','SprintIndexTaskName',N'Име на задача'),
('Sprint','SprintIndexStatus',N'Статус'),
('Sprint','SprintIndexUserInCharge',N'Отговорен потребител'),
('Sprint','SprintIndexTitle',N'Спринт '),
('Task','TasksTodayTitle',N'Име на задача'),
('Task','TasksTodayUserEffort',N'Оценено усилие'),
('Task','TasksTodayProjectName',N'Име на проект'),
('Task','TasksTodayEffort',N'Усилие'),
('Sprint','SprintIndexHeading',N'към проект: '),
('Sprint','SprintIndexHeadingTxt',N'Спринт: '),
('Task','TasksTodayNothingToDo',N'Няма задачи за днес'),
('Buttons','EnterUsername',N'Въведете потребителско име'),
('Buttons','EnterPassword',N'Въведете парола'),
('Projects','ProjectDeveloperAddHeadingTxt',N'Добавяне на потребител към проект'),
('Projects','ProjectDetailsDevInUse',N'Системата не изпълни исканата от Вас заявка. Избраният от Вас потребител участва в изпълнението на проектни задачи.'),
('Projects','ProjectDetailsDevAlreadyIn',N'Системата не изпълни исканата от Вас заявка. Избраният от Вас потребител вече участва в изпълнението на проекта.'),
('Projects','BreadCrumbProjectUndoneSecond',N'Неизпълнени задачи')

